services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=healenium
    ports:
      - "5432:5432"

  hlm-backend:
    image: healenium/hlm-backend:3.4.1
    ports:
      - "7878:7878"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/healenium
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=public
      - SHARED_SESSION=true
      - SPRING_PROFILES_ACTIVE=default